from models import SessionLocal, init_db, User, Blog
from werkzeug.security import generate_password_hash
from datetime import datetime

def seed_data():
    # Initialize the database and create tables
    init_db()

    # Create a new session
    db = SessionLocal()

    try:
        # Check if demo user exists
        existing_user = db.query(User).filter_by(email='demo@example.com').first()
        if not existing_user:
            user = User(
                name='Demo User',
                email='demo@example.com',
                password_hash=generate_password_hash('password'),
                created_at=datetime.utcnow()
            )
            db.add(user)
            db.commit()

            blog = Blog(
                user_id=user.id,
                keyword='demo,ai,seo',
                title='Welcome to AI SEO SaaS',
                meta_desc='This is a demo blog generated by seed.py',
                content_original='Your SaaS app is successfully connected to the database!',
                status='published',
                created_at=datetime.utcnow()
            )
            db.add(blog)
            db.commit()

            print("✅ Database created and demo data added successfully.")
        else:
            print("ℹ️ Demo user already exists, skipping seeding.")
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()